// rangers.js

const rangers= [
  {
    name: "Samiul Haque",
    age: 32,
    gender: "Male",
    region: "North Zone",
    yearsOfExperience: 6,
    patrolsPerWeek: 5,
    certifications: ["Wildlife Tracking", "First Aid"],
    isActive: true,
  },
  {
    name: "Rima Akter",
    age: 28,
    gender: "Female",
    region: "South Zone",
    yearsOfExperience: 4,
    patrolsPerWeek: 4,
    certifications: ["Animal Behavior", "Emergency Response"],
    isActive: true,
  },
  {
    name: "Rashed Khan",
    age: 45,
    gender: "Male",
    region: "Central Zone",
    yearsOfExperience: 20,
    patrolsPerWeek: 2,
    certifications: ["Veterinary Skills"],
    isActive: false,
  },
  {
    name: "Monira Alam",
    age: 38,
    gender: "Female",
    region: "East Zone",
    yearsOfExperience: 10,
    patrolsPerWeek: 3,
    certifications: [],
    isActive: true,
  },
  {
    name: "Tanvir Rahman",
    age: 30,
    gender: "Male",
    region: "West Zone",
    yearsOfExperience: 7,
    patrolsPerWeek: 6,
    certifications: ["Night Surveillance"],
    isActive: true,
  },
  {
    name: "Rafiq Islam",
    age: 50,
    gender: "Male",
    region: "North Zone",
    yearsOfExperience: 25,
    patrolsPerWeek: 1,
    certifications: ["Rescue Operations", "First Aid"],
    isActive: false,
  },
  {
    name: "Farzana Yasmin",
    age: 26,
    gender: "Female",
    region: "South Zone",
    yearsOfExperience: 3,
    patrolsPerWeek: 5,
    certifications: ["Wildlife Communication"],
    isActive: true,
  },
  {
    name: "Imran Kabir",
    age: 35,
    gender: "Male",
    region: "Central Zone",
    yearsOfExperience: 12,
    patrolsPerWeek: 4,
    certifications: ["Tracking", "Animal Tranquilization"],
    isActive: true,
  },
  {
    name: "Taslima Noor",
    age: 42,
    gender: "Female",
    region: "East Zone",
    yearsOfExperience: 15,
    patrolsPerWeek: 2,
    certifications: ["Veterinary Skills", "First Aid"],
    isActive: false,
  },
  {
    name: "Abdul Malek",
    age: 29,
    gender: "Male",
    region: "West Zone",
    yearsOfExperience: 5,
    patrolsPerWeek: 6,
    certifications: [],
    isActive: true,
  },
];
