const sightings =
  // sightings.js

  [
    {
      species: "Bengal Tiger",
      date: new Date("2025-06-10"),
      location: { zone: "North Zone", coordinates: [24.12, 90.25] },
      ranger: "Samiul Haque",
      notes: "Seen near waterhole",
      tags: ["rare", "solo"],
      count: 1,
    },
    {
      species: "Asian Elephant",
      date: new Date("2025-06-11"),
      location: { zone: "South Zone", coordinates: [23.87, 90.35] },
      ranger: "Rima Akter",
      notes: "Herd observed",
      tags: ["herd"],
      count: 7,
    },
    {
      species: "Peacock",
      date: new Date("2025-06-12"),
      location: { zone: "East Zone", coordinates: [23.93, 90.28] },
      ranger: "Monira Alam",
      notes: "Near ranger post",
      tags: [],
      count: 3,
    },
    {
      species: "Crocodile",
      date: new Date("2025-06-10"),
      location: { zone: "Central Zone", coordinates: [24.05, 90.31] },
      ranger: "Rashed Khan",
      notes: "Sunbathing",
      tags: ["territorial"],
      count: 2,
    },
    {
      species: "Gharial",
      date: new Date("2025-06-14"),
      location: { zone: "North Zone", coordinates: [24.15, 90.27] },
      ranger: "Samiul Haque",
      notes: "Swimming downstream",
      tags: ["endangered"],
      count: 1,
    },
    {
      species: "Hornbill",
      date: new Date("2025-06-13"),
      location: { zone: "East Zone", coordinates: [23.91, 90.3] },
      ranger: "Taslima Noor",
      notes: "Perched on tall tree",
      tags: ["rare"],
      count: 2,
    },
    {
      species: "Sloth Bear",
      date: new Date("2025-06-12"),
      location: { zone: "West Zone", coordinates: [23.85, 90.23] },
      ranger: "Tanvir Rahman",
      notes: "Crossing trail",
      tags: ["alert"],
      count: 1,
    },
    {
      species: "Python",
      date: new Date("2025-06-15"),
      location: { zone: "Jungle Zone", coordinates: [23.99, 90.4] },
      ranger: "Imran Kabir",
      notes: "Near rocks",
      tags: [],
      count: 1,
    },
    {
      species: "Otter",
      date: new Date("2025-06-16"),
      location: { zone: "Wetlands", coordinates: [24.0, 90.38] },
      ranger: "Farzana Yasmin",
      notes: "Family near water",
      tags: ["family", "playful"],
      count: 4,
    },
    {
      species: "King Cobra",
      date: new Date("2025-06-17"),
      location: { zone: "Rainforest", coordinates: [24.1, 90.45] },
      ranger: "Abdul Malek",
      notes: "Spotted crossing trail",
      tags: ["danger"],
      count: 1,
    },
  ];
