// species.js
const species = [
  {
    name: "Bengal Tiger",
    type: "Mammal",
    diet: "Carnivore",
    habitat: "Forest",
    endangered: true,
    populationEstimate: 2500,
    avgLifespan: 15,
  },
  {
    name: "Asian Elephant",
    type: "Mammal",
    diet: "Herbivore",
    habitat: "Grassland",
    endangered: true,
    populationEstimate: 4000,
    avgLifespan: 60,
  },
  {
    name: "Peacock",
    type: "Bird",
    diet: "Omnivore",
    habitat: "Forest",
    endangered: false,
    populationEstimate: 15000,
    avgLifespan: 20,
  },
  {
    name: "Crocodile",
    type: "Reptile",
    diet: "Carnivore",
    habitat: "Wetlands",
    endangered: false,
    populationEstimate: 7000,
    avgLifespan: 70,
  },
  {
    name: "Gharial",
    type: "Reptile",
    diet: "Carnivore",
    habitat: "River",
    endangered: true,
    populationEstimate: 300,
    avgLifespan: 40,
  },
  {
    name: "Hornbill",
    type: "Bird",
    diet: "Omnivore",
    habitat: "Forest",
    endangered: false,
    populationEstimate: 3200,
    avgLifespan: 35,
  },
  {
    name: "Sloth Bear",
    type: "Mammal",
    diet: "Omnivore",
    habitat: "Forest",
    endangered: true,
    populationEstimate: 5000,
    avgLifespan: 25,
  },
  {
    name: "Python",
    type: "Reptile",
    diet: "Carnivore",
    habitat: "Jungle",
    endangered: false,
    populationEstimate: 10000,
    avgLifespan: 30,
  },
  {
    name: "King Cobra",
    type: "Reptile",
    diet: "Carnivore",
    habitat: "Rainforest",
    endangered: true,
    populationEstimate: 2000,
    avgLifespan: 20,
  },
  {
    name: "Otter",
    type: "Mammal",
    diet: "Carnivore",
    habitat: "Wetlands",
    endangered: true,
    populationEstimate: 800,
    avgLifespan: 12,
  },
];
